### ISSUE TITLE
Complex send object

### ISSUE THREAD

**Issue by Mierzmit** [baseball435/NitroNet#2]
I keep getting this exception(not always) when trying to send bigger (but still pretty small 1.2mb< ) files from server to each connected client using complex send object.
<b>
java.lang.ArrayIndexOutOfBoundsException
    at com.jmr.wrapper.common.complex.ReceivedComplexObject.formObject(ReceivedComplexObject.java:77)
    at com.jmr.wrapper.common.complex.ComplexManager.handlePiece(ComplexManager.java:57)
    at com.jmr.wrapper.common.utils.PacketUtils.handleComplexPiece(PacketUtils.java:211)
    at com.jmr.wrapper.client.threads.ClientTcpReadThread.run(ClientTcpReadThread.java:67)
</b>
I using fixed number of 20 splits as I won't have any bigger files.
This is code I using:
<b>
for (Connection c : ConnectionManager.getInstance().getConnections()) {
                c.sendComplexObjectTcp(packet, 20);
        }
</b>
Even when I split it and send only to one client it give exception.

**Comment by jmrapp1** [comment]
The problem has been fixed. It seems that it was an issue with some byte arrays being converted to int's incorrectly. Sorry for the delay. Should be working now.
